### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by irenecavros** [shiwanisapkota/shiwanisapkota-MADA-portfolio#3]
Hey Shiwani! First of all, great job in replicating that visualization. The hovermode is very cool and overall I think the level it matches the plot from Our World in Data is GREAT. The main difference between the two to me are the interactive elements in the hovermode display and also the legend. I have never created interactive plots before so I am not sure how complicated these would be to tweak, but here are two suggestions for improvement: 

1. Legend in example is interactive: when you click one of the forms of cancer it grays out the other lines
2. When you hover over a year on the plot, in the example there are points matching the color of each line that show up

**Comment by shiwanisapkota** [comment]
Hey Irene!! Thanks a lot for your comments and feedbacks. Addressing your issues:
1. I could not figure out the individual form of cancer being active and others graying out while hovering on that particular type of cancer but if you `click` a particular type of cancer then that individual form of cancer becomes active and others grey out similar to the original plot. So, basically I leaned towards creating the clicking option for the individual type of cancer instead of hovering option.

2. Regarding the points matching the color of each line that show up, I could not figure out that part and left as it is.

Please let me know if you have any further questions. Thanks a lot!!
